//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplanse.
        /// </summary>
        public static string Airplanse {
            get {
                return ResourceManager.GetString("Airplanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight lines.
        /// </summary>
        public static string Flight_lines {
            get {
                return ResourceManager.GetString("Flight_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flights.
        /// </summary>
        public static string Flights {
            get {
                return ResourceManager.GetString("Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffings.
        /// </summary>
        public static string Staffings {
            get {
                return ResourceManager.GetString("Staffings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWM Airlines Management.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }
    }
}
